<?php

/**
 * @file
 * Contains project_admin.module.
 */

function project_admin_page_attachments(array &$attachments) {
  $config = \Drupal::config('system.theme');
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme == $config->get('admin')) {
    $attachments['#attached']['library'][] = 'project_admin/admin-overrides';
  }
}

/**
 * Implements hook_theme().
 *
 * Note that this isn't necessary if the template is in the site theme rather than a module.
 * See https://www.drupal.org/docs/8/theming/twig/twig-template-naming-conventions
 */
function project_admin_theme($existing, $type, $theme, $path) {
  return array(
    'field__paragraph__field_heading' => array(
      'template' => 'field--paragraph--field-heading',
      'base hook' => 'field',
    ),
    'field__paragraph__field_links' => array(
      'template' => 'field--paragraph--field-links',
      'base hook' => 'field',
    ),
    'field__paragraph__field_section_title__accordion_item' => array(
      'template' => 'field--paragraph--field-section-title--accordion-item',
      'base hook' => 'field',
    ),
    'field__paragraph__field_section_title__tab_item' => array(
      'template' => 'field--paragraph--field-section-title--tab-item',
      'base hook' => 'field',
    ),
  );
}
